[package]
name = "simple_websocket_server"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "simple_rust_server"
path = "simple_rust_server.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
